package book

// Code generated by "weaver generate". DO NOT EDIT.
import (
	"context"
	"fmt"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"github.com/devfullcycle/service-weaver-demo/components/comment"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
	"time"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/devfullcycle/service-weaver-demo/components/book/BookComponent",
		Iface: reflect.TypeOf((*BookComponent)(nil)).Elem(),
		New:   func() any { return &bookComponent{} },
		LocalStubFn: func(impl any, tracer trace.Tracer) any {
			return bookComponent_local_stub{impl: impl.(BookComponent), tracer: tracer}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return bookComponent_client_stub{stub: stub, addMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/devfullcycle/service-weaver-demo/components/book/BookComponent", Method: "Add"}), listMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "github.com/devfullcycle/service-weaver-demo/components/book/BookComponent", Method: "List"})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return bookComponent_server_stub{impl: impl.(BookComponent), addLoad: addLoad}
		},
	})
}

// Local stub implementations.

type bookComponent_local_stub struct {
	impl   BookComponent
	tracer trace.Tracer
}

func (s bookComponent_local_stub) Add(ctx context.Context, a0 Book) (err error) {
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "book.BookComponent.Add", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Add(ctx, a0)
}

func (s bookComponent_local_stub) List(ctx context.Context) (r0 []Book, err error) {
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "book.BookComponent.List", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.List(ctx)
}

// Client stub implementations.

type bookComponent_client_stub struct {
	stub        codegen.Stub
	addMetrics  *codegen.MethodMetrics
	listMetrics *codegen.MethodMetrics
}

func (s bookComponent_client_stub) Add(ctx context.Context, a0 Book) (err error) {
	// Update metrics.
	start := time.Now()
	s.addMetrics.Count.Add(1)

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "book.BookComponent.Add", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
		err = s.stub.WrapError(err)

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
			s.addMetrics.ErrorCount.Add(1)
		}
		span.End()

		s.addMetrics.Latency.Put(float64(time.Since(start).Microseconds()))
	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	(a0).WeaverMarshal(enc)
	var shardKey uint64

	// Call the remote method.
	s.addMetrics.BytesRequest.Put(float64(len(enc.Data())))
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	if err != nil {
		return
	}
	s.addMetrics.BytesReply.Put(float64(len(results)))

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

func (s bookComponent_client_stub) List(ctx context.Context) (r0 []Book, err error) {
	// Update metrics.
	start := time.Now()
	s.listMetrics.Count.Add(1)

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "book.BookComponent.List", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
		err = s.stub.WrapError(err)

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
			s.listMetrics.ErrorCount.Add(1)
		}
		span.End()

		s.listMetrics.Latency.Put(float64(time.Since(start).Microseconds()))
	}()

	var shardKey uint64

	// Call the remote method.
	s.listMetrics.BytesRequest.Put(0)
	var results []byte
	results, err = s.stub.Run(ctx, 1, nil, shardKey)
	if err != nil {
		return
	}
	s.listMetrics.BytesReply.Put(float64(len(results)))

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_slice_Book_727dace9(dec)
	err = dec.Error()
	return
}

// Server stub implementations.

type bookComponent_server_stub struct {
	impl    BookComponent
	addLoad func(key uint64, load float64)
}

// GetStubFn implements the stub.Server interface.
func (s bookComponent_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Add":
		return s.add
	case "List":
		return s.list
	default:
		return nil
	}
}

func (s bookComponent_server_stub) add(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 Book
	(&a0).WeaverUnmarshal(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Add(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s bookComponent_server_stub) list(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.List(ctx)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_slice_Book_727dace9(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

// AutoMarshal implementations.

var _ codegen.AutoMarshal = &Book{}

func (x *Book) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Book.WeaverMarshal: nil receiver"))
	}
	enc.String(x.ID)
	enc.String(x.Title)
	enc.String(x.Author)
	serviceweaver_enc_slice_Comment_2c83ce82(enc, x.Comments)
}

func (x *Book) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Book.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.String()
	x.Title = dec.String()
	x.Author = dec.String()
	x.Comments = serviceweaver_dec_slice_Comment_2c83ce82(dec)
}

func serviceweaver_enc_slice_Comment_2c83ce82(enc *codegen.Encoder, arg []comment.Comment) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		(arg[i]).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_slice_Comment_2c83ce82(dec *codegen.Decoder) []comment.Comment {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]comment.Comment, n)
	for i := 0; i < n; i++ {
		(&res[i]).WeaverUnmarshal(dec)
	}
	return res
}

// Encoding/decoding implementations.

func serviceweaver_enc_slice_Book_727dace9(enc *codegen.Encoder, arg []Book) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		(arg[i]).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_slice_Book_727dace9(dec *codegen.Decoder) []Book {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]Book, n)
	for i := 0; i < n; i++ {
		(&res[i]).WeaverUnmarshal(dec)
	}
	return res
}
